settings:
  title: 'Status Page'
  url: 'https://status.addismap.workers.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: 'Some checks failed'

monitors:
  - id: addismap-com # unique identifier
    name: addismap.com
    description: 'AddisMap.com' # default=empty
    url: 'https://www.addismap.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false

  - id: map-et
    name: map.et
    description: 'Map.et'
    url: 'https://map.et'
    method: GET
    expectStatus: 302

  - id: pt-addismap-com
    name: Public Transport API
    url: 'https://pt.addismap.com/'
    method: GET
    expectStatus: 200
